/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pressedbutton;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.KeyStroke;

/**
 *
 * @author aleksph
 */
public class MyFrame extends javax.swing.JFrame implements KeyListener{
    //JLabel lblText;
    ImageIcon icon;
    public MyFrame() {
        initComponents();
        String fullpath = "D:/11i/Alex Hritsov/BackgroundLoop/src/backgroundloop";
        //Sets the image to be displayed as an icon
        //icon = new ImageIcon("/rocket.jfif"); 
        ImageIcon car = new ImageIcon("src/pressedbutton/yellowCar.png");
        Image img = car.getImage();
        Image imgScale = img.getScaledInstance(lblText.getWidth(),lblText.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        lblText.setIcon(scaledIcon);
        
        
        
        System.out.println("VLIZAA v MYFRAME");
        //lblTextKeyPressed();
        this.addKeyListener(this);
    }
    //public abstract void keyPressed(KeyEvent e);  

    /**
     * Creates new form PressedButtonAll
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCanvas = new javax.swing.JPanel();
        lblText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblText.setBackground(new java.awt.Color(102, 102, 255));
        lblText.setForeground(new java.awt.Color(255, 0, 51));
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pressedbutton/carImage.png"))); // NOI18N
        lblText.setText("asdasd");
        lblText.setOpaque(true);
        lblText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTextKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlCanvasLayout = new javax.swing.GroupLayout(pnlCanvas);
        pnlCanvas.setLayout(pnlCanvasLayout);
        pnlCanvasLayout.setHorizontalGroup(
            pnlCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCanvasLayout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        pnlCanvasLayout.setVerticalGroup(
            pnlCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCanvasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTextKeyPressed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_lblTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel pnlCanvas;
    // End of variables declaration//GEN-END:variables
    public void paintComponents(Graphics g){
        super.paintComponents(g);
        //g.drawImage
        //g.drawImage(icon, ERROR, ERROR, this);
    }
    
    
    @Override
    public void keyTyped(KeyEvent arg0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent evt) {
               //lblText.setBackground(Color.red);
        System.out.println("VLIZAA v lblTextKeyPressed");
        int x = lblText.getX();
        int y = lblText.getY();
        
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            lblText.setLocation(x-20,y);
        }else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            lblText.setLocation(x+20,y);
        }else if(evt.getKeyCode() == KeyEvent.VK_UP){
            lblText.setLocation(x,y-20);
        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            lblText.setLocation(x,y+20);
        }else if(evt.getKeyCode() == KeyEvent.VK_UP && evt.getKeyCode() == KeyEvent.VK_LEFT){
            lblText.setLocation(x-20,y+20);
        }
    }

    @Override
    public void keyReleased(KeyEvent arg0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
/*    MyFrame(){  
      //this.setDefaultCloseOperation(pnlCanvas.EXIT_ON_CLOSE);
      this.setSize(500,500);
      this.setLayout(null);
      this.addKeyListener(this);

      icon = new ImageIcon("rocket.png");

      //label = new JLabel();
      lblText.setBounds(0, 0, 100, 100);
      lblText.setIcon(icon);
      //label.setBackground(Color.red);
      //label.setOpaque(true);
      //this.getContentPane().setBackground(Color.black);
      this.add(lblText);
      this.setVisible(true);
    }*/





}
