
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aleksph
 */
public class LoginMenu extends javax.swing.JFrame {
    static DynamicArray clients = new DynamicArray();

    /**
     * Creates new form LoginMenu
     */
    Random random = new Random();
    public LoginMenu() {
        
        String[] names = {"Ali", "Hristo","Petko","Blago","Kiro"};
        String[] surnames = {"Bobo", "Ivan","Ivana","Huiev","Cokov"};
        int[] pins = {1234,4567,8901,2345,6789};
        System.out.println("pins+"+pins[0]);
        for(int i = 0;i<5;i++){
           clients.add(new Client(names[i], surnames[i] , 99000.0 , 10000, ""+pins[i]));
        }
        for(int i = 0;i<5;i++){
            System.out.println(clients.getElement(i).getName());
            System.out.println(clients.getElement(i).getSurName());
            System.out.println(clients.getElement(i).getKredit());
            System.out.println(clients.getElement(i).getMoney());
            System.out.println(clients.getElement(i).getPin());
            System.out.println("");
        }
        clients.getElement(0).setMoney(125);
        clients.getElement(1).setMoney(100);
        clients.getElement(2).setMoney(50);
        clients.getElement(3).setMoney(300);
        clients.getElement(4).setMoney(200);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BankCalulator = new javax.swing.JPanel();
        bank_name1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMoney1 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        btnLoginMenu = new javax.swing.JButton();
        txtErrors = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BankCalulator.setBackground(new java.awt.Color(20, 59, 121));

        bank_name1.setBackground(new java.awt.Color(255, 255, 255));
        bank_name1.setForeground(new java.awt.Color(255, 255, 255));
        bank_name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bank_name1.setText("Log In an Account (LIA)");
        bank_name1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_bank.jfif"))); // NOI18N

        txtMoney1.setBackground(new java.awt.Color(255, 255, 255));
        txtMoney1.setForeground(new java.awt.Color(255, 255, 255));
        txtMoney1.setText("Pin:");

        btnLoginMenu.setBackground(new java.awt.Color(51, 51, 255));
        btnLoginMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginMenu.setText("Log in");
        btnLoginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginMenuActionPerformed(evt);
            }
        });

        txtErrors.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout BankCalulatorLayout = new javax.swing.GroupLayout(BankCalulator);
        BankCalulator.setLayout(BankCalulatorLayout);
        BankCalulatorLayout.setHorizontalGroup(
            BankCalulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankCalulatorLayout.createSequentialGroup()
                .addGroup(BankCalulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BankCalulatorLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(bank_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BankCalulatorLayout.createSequentialGroup()
                        .addGroup(BankCalulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BankCalulatorLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(BankCalulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(BankCalulatorLayout.createSequentialGroup()
                                        .addComponent(txtMoney1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BankCalulatorLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(BankCalulatorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BankCalulatorLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnLoginMenu)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        BankCalulatorLayout.setVerticalGroup(
            BankCalulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankCalulatorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(bank_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BankCalulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BankCalulatorLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(BankCalulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BankCalulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMoney1)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BankCalulatorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoginMenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BankCalulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BankCalulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnLoginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginMenuActionPerformed
        // TODO add your handling code here:
        LoginMenu objClients = new LoginMenu();
        
        String name = txtName.getText();
        String pin = password.getText();
        
        for(int i = 0; i < objClients.clients.getSize();i++){
            if(objClients.clients.getElement(i).getName().equals(name) && objClients.clients.getElement(i).getPin().equals(pin)){
                this.dispose();
                new SAAS().setVisible(true);
            }else{
                txtErrors.setText("Wrong name or pin");
            }
        }
        
    }//GEN-LAST:event_btnLoginMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BankCalulator;
    private javax.swing.JLabel bank_name1;
    private javax.swing.JButton btnLoginMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel txtErrors;
    private javax.swing.JLabel txtMoney1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
